datasets:
  safety_finetune:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
            - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/aokvqa/aokvqa_v1p0_train.json
          storage:
            - /path/to/your/local/drive/metavqa_final/vqa/training/single_frame_processed/Waymo/static_qa0.json
        val:
          url:
            - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/aokvqa/aokvqa_v1p0_val.json
          storage:
            - /path/to/your/local/drive/metavqa_final/vqa/validation/single_frame_processed/Waymo/static_qa0.json
        test:
          url:
            - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/aokvqa/aokvqa_v1p0_test.json
          storage:
            - /path/to/your/local/drive/metavqa_final/vqa/validation/single_frame_processed/Waymo/static_qa0.json
      images:
        storage: /path/to/your/local/drive/metavqa_final